name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            APP_DIR="/rhodium-dashboard"
            REPO_URL="git@github.com:InefableKoumba/rhodium-dashboard.git"

            if [ ! -d "$APP_DIR" ]; then
              echo "Cloning repository..."
              git clone $REPO_URL $APP_DIR
            fi

            cd $APP_DIR
            git pull origin main
            bun install --frozen-lockfile
            bun run build
            pm2 restart rhodium-dashboard || pm2 start bun --name "rhodium-dashboard" -- start
